import Vue from "vue";
import {
    Icon,
    Tab,
    Tabs,
    List,
    Cell,
    Button,
    Popup,
    Field,
    Dialog,
    Toast,
    Swipe,
    SwipeItem,
    Area,
    NavBar,
    NoticeBar,
    ActionSheet,
    CellGroup,
    Image,
    Sticky,
    PullRefresh,
    Tag,
    Picker,
    Divider,
    Step,
    Steps,
    Panel,
    Collapse,
    CollapseItem,
    Loading,
    Grid,
    GridItem,
    Row,
    Col
} from "vant";

Vue.use(Icon);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(List);
Vue.use(Cell);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Field);
Vue.use(Dialog);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Area);
Vue.use(NavBar);
Vue.use(NoticeBar);
Vue.use(CellGroup);
Vue.use(Image);
Vue.use(Sticky);
Vue.use(ActionSheet);
Vue.use(PullRefresh);
Vue.use(Tag);
Vue.use(Picker);
Vue.use(Divider);
Vue.use(Step);
Vue.use(Steps);
Vue.use(Panel);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Loading);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Row);
Vue.use(Col);

